language: node_js
node_js:
  - 8
install: yarn install
script: yarn build && yarn test
env:
  global:
  - secure: UzhXRA3TZbTqBuh17gOlid4d9tpa4maBaDI7SiJpSQBOH/hRQCfTWr/ZfQLr9og0e8PT1d5d0UzWPbu3WbiL9Uiq2yNj3uBqJ0cdhxLvxoxsIl8oPd37/Xa8cI7Cmz2YBIwnnEgUQKbydffQGIA1IGkZMRnP4Aj9BY5+A+QabW8=
  - secure: rtcrP/E6FhoH18wiSYeJKBgqnSweIi8miAD2jU+A9J9YBwNhOeR6A1S9LL0Xmi8Q4Vk2NyyckVFrfnWq6aEj14sbKqVXEsVkM7Iuw2MrqS4XLgAARYgvz1TcUhxFkZcfu53m2M4iDcaJdu7Yzw5rF2jeb7yI1dZZ7vH8PbiF+p8=
notifications:
  email:
    on_success: never
    on_failure: change
